---

- name: "Common Desktop System: Arch"
  hosts: all

  collections:
    - name: community.general

  tasks:
    - name: "Add Chaotic-AUR"
      block:
        - name: "Add key"
          command: pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
        - name: "Sign key"
          command: pacman-key --lsign-key FBA220DFC880C036
        - name: "Install Mirrorlist"
          command: pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
        - name: "Add repo entry"
          ansible.builtin.blockinfile:
            path: /etc/pacman.conf
            block: |

              [chaotic-aur]
              Include = /etc/pacman.d/chaotic-mirrorlist
    - name: "Update System"
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: "Install Aura & Paru"
      community.general.pacman:
        state: latest
        name: aura paru
    - name: "Install Base Packages"
      community.general.pacman:
        executable: aura
        state: latest
        name: pacseek btop gtop xterm acpi vim qtile picom libreoffice-fresh notmuch thunderbird birdtray librewolf firefox-developer-edition nyxt transmission-gtk transmission-cli ueberzug lf ranger exa bat fd ripgrep vscodium emacs-nativecomp neovim python-pynvim ctags libvterm cmake gcc cool-retro-term kitty tilix contour-git blender steam-native-runtime lutris kicad linux-tkg-bmq linux-tkg-bmq-headers ardour lmms musescore wireshark-qt wireshark-cli speedtest-cli fish pypy3 update-grub element-desktop copyq network-manager-applet cbatticon volumeicon pamac-nosnap pcmanfm-gtk3 nautilus nemo nemo-audio-tab nemo-emblems nemo-fileroller nemo-image-converter nemo-preview nemo-python nemo-seahorse nemo-share nemo-terminal lxappearance-gtk3 lxsession-gtk3 kvantum qt5ct feh sxiv gamemode blueman qjackctl sof-firmware alsa-ucm-conf pipewire pipewire-alsa alsa-utils pulsemixer pavucontrol pipewire-pulse pipewire-jack wireplumber easyeffects obs-studio chrony fcron rofi rofimoji rofi-pass rofi-calc neofetch keepassxc pass file-roller filezilla tor torsocks onionshare retroshare torbrowser-launcher galculator qalculate-gtk ttf-iosevka-nerd searx curl wget curlie xss-lock i3lock-color xdotool virt-manager gnome-boxes libvirt dnsmasq openbsd-netcat gettext ebtables qemu-desktop qemu-emulators-full lvm2 swtpm openssh glava picard mpd ncmpcpp termdown dbeaver touchegg touche arc-gtk-theme arc-icon-theme vlc mpv mpv-mpris celluloid clementine ytfzf yt-dlp youtube-dl fzf playerctl krita inkscape gimp cheese bleachbit stacer docker zellij tmux geany lapce helix kakoune notepadqq xpad skippy-xd-git hyprland-git waybar-hyprland-git newsboat atuin gnome-boxes scrot flameshot
    - name: "Install Base Packages (AUR)"
      community.general.pacman:
        executable: aura
        state: latest
        extra_args: "-A"
        name: gruvbox-material-gtk-theme-git gruvbox-material-icon-theme-git xcursor-simp1e-gruvbox-dark visual-studio-code-bin nvidia-vaapi-driver-git boop-gtk-bin # picom-jonaburg-git
    - name: "Update Grub"
      command: update-grub
