---

- name: "Common Desktop System: Arch"
  hosts: all

  collections:
    - name: community.general

  tasks:
    - name: "Add Chaotic-AUR"
      block:
        - name: "Add key"
          command: pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
        - name: "Sign key"
          command: pacman-key --lsign-key FBA220DFC880C036
        - name: "Install Mirrorlist"
          command: pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
        - name: "Add repo entry"
          ansible.builtin.blockinfile:
            path: /etc/pacman.conf
            block: |

              [chaotic-aur]
              Include = /etc/pacman.d/chaotic-mirrorlist
    - name: "Update System"
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: "Install Aura & Paru"
      community.general.pacman:
        state: latest
        name: aura paru
    - name: "Install Base Packages"
      community.general.pacman:
        executable: aura
        state: latest
        name: stow pacseek hunspell hunspell-en_us aspell aspell-en brightnessctl apparmor xdg-user-dirs flite vkd3d wine innoextract wired btop gtop xterm acpi vim go skeuos-gtk bpython qtile python-dbus-next python-pywlroots python-setproctitle stumpwm stumpwm-contrib-git clisp quicklisp libreoffice-fresh notmuch isync thunderbird birdtray librewolf firefox-developer-edition vivaldi vivaldi-ffmpeg-codecs nyxt transmission-gtk transmission-cli ueberzug lf xplr ranger exa bat fd ripgrep vscodium mono dotnet-runtime dotnet-sdk emacs-nativecomp neovim python-pynvim ctags libvterm cmake gcc cool-retro-term kitty tilix contour-git blender steam-native-runtime lutris kicad linux-headers linux-tkg-bmq linux-tkg-bmq-headers linux-drm-next-git linux-drm-next-headers-git ardour lmms musescore wireshark-qt wireshark-cli speedtest-cli nodejs npm fish nushell pypy3 update-grub element-desktop clipmenu copyq network-manager-applet cbatticon volumeicon pamac-nosnap pcmanfm-gtk3 nautilus nemo nemo-audio-tab nemo-emblems nemo-fileroller nemo-image-converter nemo-preview nemo-python nemo-seahorse nemo-share nemo-terminal lxappearance-gtk3 lxsession-gtk3 kvantum qt5ct chafa libsixel feh sxiv gamemode blueman qjackctl sof-firmware alsa-ucm-conf pipewire pipewire-alsa alsa-utils pulsemixer pavucontrol pipewire-pulse pipewire-jack wireplumber easyeffects obs-studio chrony fcron rofi rofimoji rofi-pass rofi-calc wofi neofetch keepassxc pass file-roller filezilla tor torsocks onionshare retroshare torbrowser-launcher galculator qalculate-gtk powerline-fonts ttf-iosevka ttf-iosevka-nerd searx curl wget curlie traceroute mtr xss-lock i3lock-color xdotool virt-manager gnome-boxes libvirt dnsmasq openbsd-netcat gettext ebtables qemu-desktop qemu-emulators-full lvm2 swtpm openssh glava picard mpd ncmpcpp termdown dbeaver arc-gtk-theme arc-icon-theme handbrake lollypop cmus vlc atomicparsley mpv mpv-mpris celluloid strawberry ytfzf yt-dlp youtube-dl fzf playerctl krita inkscape gimp cheese bleachbit stacer docker zellij tmux geany lapce helix kakoune notepadqq xpad skippy-xd-git hyprland-git newsboat atuin gnome-boxes scrot flameshot cardinal cardinal-data cardinal-clap carla-git python-evdev xf86-input-evdev xf86-input-libinput libinput xorg-xwininfo asciiquarium gnucash libdbi-drivers perl-date-manip perl-finance-quote tlpui veracrypt zoxide rustup remmina moonlight-qt man-db redshift flashfocus jami-qt tela-icon-theme-git tela-circle-icon-theme-git orchis-theme-git kvantum-theme-orchis-git cups weechat weechat-matrix #a picom picom-ibhagwan-git # dunst # emacs-pgtk-native-comp-git emacs touchegg touche clementine
    - name: "Install Base Packages (AUR)"
      community.general.pacman:
        executable: aura
        state: latest
        extra_args: "-A"
        name: gruvbox-material-gtk-theme-git gruvbox-material-icon-theme-git gruvbox-dark-gtk gruvbox-dark-icons-gtk skeuowaita-git xcursor-simp1e-gruvbox-dark visual-studio-code-bin nvidia-vaapi-driver-git bumblebee bbswitch-dkms primus lib32-virtualgl lib32-primus boop-gtk-bin wtfutil-bin bigtime clock-tui pass-import ly waybar-hyprland-git jdk17-graalvm-bin native-image-jdk17-bin jdk19-graalvm-bin native-image-jdk19-bin picom-ftlabs-git # coreapps-meta # gtkdialog # picom-jonaburg-git capitaine-cursors-sainnhe-git
    - name: "Update Grub"
      command: update-grub
