---

- name: "Common Desktop System: Arch"
  hosts: all

  tasks:
    - name: "Add Chaotic-AUR"
      block:
        - name: "Add key"
          command: pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
        - name: "Sign key"
          command: pacman-key --lsign-key FBA220DFC880C036
        - name: "Install Mirrorlist"
          command: pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
        - name: "Add repo entry"
          ansible.builtin.blockinfile:
            path: /etc/pacman.conf
            block: |

              [chaotic-aur]
              Include = /etc/pacman.d/chaotic-mirrorlist
    - name: "Update System"
      command: pacman -Syyu --noconfirm
    - name: "Install Base Packages"
      command: pacman -S --needed --noconfirm btop xterm acpi vim qtile thunderbird firefox-developer-edition nyxt transmission-gtk transmission-cli lf exa bat fd ripgrep emacs-pgtk-native-comp-git neovim python-pynvim ctags libvterm cmake gcc paru aura cool-retro-term kitty blender steam-native-runtime lutris kicad linux-tkg-bmq linux-tkg-bmq-headers ardour wireshark-qt wireshark-cli speedtest-cli fish pypy3 update-grub element-desktop copyq network-manager-applet cbatticon volumeicon pamac-aur pcmanfm-gtk3 lxappearance-gtk3 lxsession-gtk3 feh sxiv gamemode blueman pipewire pipewire-alsa pipewire-pulse pipewire-jack wireplumber easyeffects alsa-support obs-studio chrony fcron rofi rofimoji rofi-pass rofi-calc neofetch keepassxc pass file-roller tor torsocks onionshare torbrowser-launcher galculator qalculate ttf-iosevka-nerd searx curl wget curlie
    - name: "Update Grub"
      command: update-grub
