##########-------====-------##########
# -= Dunkmania101's Zellij Config =- #
##########-------====-------##########


##########
# UI/Theme Settings
themes:
  gruvbox-dark:
    bg: [40, 40, 40]
    red: [204, 36, 29]
    green: [152, 151, 26]
    yellow: [215, 153, 33]
    blue: [69, 133, 136]
    magenta: [177, 98, 134]
    orange: [214, 93, 14]
    fg: [213, 196, 161]
    cyan: [104, 157, 106]
    black: [60, 56, 54]
    white: [251, 241, 199]
  one-half-dark:
    bg: [40, 44, 52]
    red: [227, 63, 76]
    green: [152, 195, 121]
    yellow: [229, 192, 123]
    blue: [97, 175, 239]
    magenta: [198, 120, 221]
    orange: [216, 133, 76]
    fg: [220, 223, 228]
    cyan: [86, 182, 194]
    black: [27, 29, 35]
    white: [233, 225, 254]

theme: gruvbox-dark

ui:
  pane_frames:
    rounded_corners: true
##########

